image: php

stages:
  - bake
  - deploy

bake:
  stage: bake
  script:
    - tools/bake.sh
  artifacts:
    paths:
      - game.min.js

pages:
  stage: deploy
  script:
    - mkdir public
    - mv media public
    - mv tools/index.html public
    - mv game.min.js public
  artifacts:
    paths:
      - public
  only:
    - master
