#language: php
#php:
#- '5.5'
#- '5.4'

script:
  - mkdir pub
  - tools/bake.sh
  - mv game.min.js pub
  - mv media pub
  - mv tools/index.html pub
  #- rm -r weltmeister.html tools/ lib/ index.js server.py
  - ls
  - ls pub

deploy:
  local-dir: pub
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
