#language: php
#php:
#- '5.5'
#- '5.4'

script:
  - tools/bake.sh
  - mv tools/index.html .
  - rm -r weltmeister.html tools/ lib/ index.js server.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
